env:
  browser: true
  es2021: true
extends:
  - bayathy
  - plugin:storybook/recommended
parser: "@typescript-eslint/parser"
parserOptions:
  project: ./tsconfig.json

rules:
  "import/export": off
  "unicorn/prefer-export-from": off
  "no-unused-vars": off
  "unicorn/prefer-node-protocol": off